### ISSUE TITLE
Error: Request failed with status code 500

### ISSUE THREAD

**Issue by yyang2018mel** [joshcai/leetcode-sync#29]
I used to run the action successfully. but recently I always get this error.

[Wed, 28 Dec 2022 10:29:13 GMT] Getting submission from LeetCode, offset 0
[Wed, 28 Dec 2022 10:2[9](https://github.com/yyang2018mel/LeetCode/actions/runs/3793355682/jobs/6450389554#step:2:10):14 GMT] Getting submission from LeetCode, offset 20
[Wed, 28 Dec 2022 [10](https://github.com/yyang2018mel/LeetCode/actions/runs/3793355682/jobs/6450389554#step:2:11):29:16 GMT] Error fetching submissions, retrying in 1 seconds...
[Wed, 28 Dec 2022 10:29:17 GMT] Error fetching submissions, retrying in 3 seconds...
[Wed, 28 Dec 2022 10:29:21 GMT] Error fetching submissions, retrying in 9 seconds...
[Wed, 28 Dec 2022 10:29:31 GMT] Error fetching submissions, retrying in 27 seconds...
[Wed, 28 Dec 2022 10:29:59 GMT] Error fetching submissions, retrying in 81 seconds...
[Wed, 28 Dec 2022 10:31:21 GMT] Error: Request failed with status code 500
    at createError (/home/runner/work/_actions/joshcai/leetcode-sync/v1.5/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/runner/work/_actions/joshcai/leetcode-sync/v1.5/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/joshcai/leetcode-sync/v1.5/node_modules/axios/lib/adapters/http.js:269:[11](https://github.com/yyang2018mel/LeetCode/actions/runs/3793355682/jobs/6450389554#step:2:12))
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:[12](https://github.com/yyang2018mel/LeetCode/actions/runs/3793355682/jobs/6450389554#step:2:13))
    at processTicksAndRejections (node:internal/process/task_queues:83:[21](https://github.com/yyang2018mel/LeetCode/actions/runs/3793355682/jobs/6450389554#step:2:22))
Error: Error: Request failed with status code 500

**Comment by Suvraneel** [comment]
@joshcai  +1 to this
I found & tried this out for the 1st time today... 
[Workflow Run](https://github.com/Suvraneel/LeetCode/actions/runs/3836763491/jobs/6531288535)

![image](https://user-images.githubusercontent.com/63473496/210525212-427ba30c-120e-4b1d-94be-a6b78e961f87.png)

**Comment by joshcai** [comment]
Thanks for the reports, does look like a bug. Do you know if it fails deterministically with the same offset numbers? I'm wondering if the final fetch is the issue or if it's some kind of flakiness. 

I wasn't able to reproduce yet, but I'll try to look at this more over the weekend when I get back home from the holidays. Sorry for the inconvenience!

**Comment by MahmoudAbdullah99** [comment]
I had the same problem
![image](https://user-images.githubusercontent.com/54509170/210892407-62b201a8-59ae-4eca-b6b6-a9b469e28cd8.png)

**Comment by joshcai** [comment]
Hmm I still wasn't able to reproduce this and had a successful run recently, do any of you guys mind sharing info on how to reproduce? e.g. potentially sending your LeetCode credentials privately to see if it's related to the LeetCode account?

**Comment by MahmoudAbdullah99** [comment]
Of course, how can I reach you?
