### ISSUE TITLE
HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by ZyLyao** [joshcai/leetcode-sync#30]
Run joshcai/leetcode-sync@v1.5
[Tue, 10 Jan 2023 01:31:51 GMT] Getting submission from LeetCode, offset 0
[Tue, 10 Jan 2023 01:31:51 GMT] Default branch for ZyLyao/My-Leetcode-Practice: main
[Tue, 10 Jan 2023 01:31:51 GMT] Syncing 3 submissions...
[Tue, 10 Jan 2023 01:31:51 GMT] Committing solution for add_two_integers...
[Tue, 10 Jan 2023 01:31:51 GMT] HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/joshcai/leetcode-sync/v1.5/node_modules/@octokit/rest/node_modules/@octokit/request/dist-node/index.js:[8](https://github.com/ZyLyao/My-Leetcode-Practice/actions/runs/3879305309/jobs/6616411997#step:2:9)8:21
    at processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/ZyLyao/My-Leetcode-Practice/actions/runs/3879305309/jobs/6616411997#step:2:10)6:5)
    at async commit (/home/runner/work/_actions/joshcai/leetcode-sync/v1.5/src/action.js:69:24)
    at async Object.sync (/home/runner/work/_actions/joshcai/leetcode-sync/v1.5/src/action.js:240:34)
    at async main (/home/runner/work/_actions/joshcai/leetcode-sync/v1.5/index.js:31:3)
Error: HttpError: Resource not accessible by integration

**Comment by GrayBurford** [comment]
Hello Joshcai,

I receive the same error as ZyLyao above when trying to sync for the first time (looking to sync my previously completed Leetcode problems with GitHub).

![image](https://user-images.githubusercontent.com/90840369/212492786-edd22b11-029e-4fc6-96fb-7bdcd94d12fb.png)

**Comment by ZyLyao** [comment]
Hi, GrayBurford

I had a few successful runs after setting up private token of my GitHub account. The action is not finally setup as I do not understand what the actual issue is. Perhaps you can try setting the token and see if that works for you. 

Zeyi

**Comment by GrayBurford** [comment]
Hi ZyLyao,

Are you referring to GitHub's Personal Access Token? Thank you for your reply!

Gray

**Comment by GrayBurford** [comment]
ZyLyao,

Thank you, will try it out.

Gray

**Comment by PabloCuestaMorer** [comment]
Yes. If you hardcode a classic token in the workflow. It works. Until a fix comes out, it's the only option that has worked for me. If anyone finds a better one, let me know.

Pablo.

**Comment by saumya-tiwari** [comment]
<img width="723" alt="image" src="https://github.com/joshcai/leetcode-sync/assets/28824897/e60520d1-0860-4ade-adf1-ad7b7f50cdab">
you can check this as well. Mine was set as Readonly. @ZyLyao

**Comment by ZyLyao** [comment]
> <img alt="image" width="723" src="https://user-images.githubusercontent.com/28824897/248770583-e60520d1-0860-4ade-adf1-ad7b7f50cdab.png"> you can check this as well. Mine was set as Readonly. @ZyLyao

I will try this. Thanks for the reply, @saumya-tiwari.
